#define MEMORY_SIZE 65536
#define BLOCK_SIZE 128
#define NUMBER_OF_SETS 8
#define ASSOCIATIVITY 4

#define MAX_VALUE 255

#define REST_OF_FLUSH_COMMAND_TEXT "LUSH"
#define REST_OF_MISS_RATE_COMMAND_TEXT "R"

#define SUCCESS 0
#define ERROR -1
#define ERROR_INVALID_ARGUMENTS_AMOUNT -2
#define ERROR_INVALID_PARAMETERS -3
#define ERROR_INVALID_COMMAND -4
#define ERROR_INVALID_ADDRESS -5
#define ERROR_INVALID_VALUE -6
#define ERROR_NON_EXISTENT_FILE -7

#define ARGUMENTS_EXECUTABLE 2
#define ARGUMENTS_READ 1
#define ARGUMENTS_WRITE 2

#define FLUSH_INDICATOR 'F'
#define WRITE_INDICATOR 'W'
#define READ_INDICATOR 'R'
#define MISS_RATE_INDICATOR 'M'
