#define MEMORY_SIZE 65536
#define BLOCK_SIZE 128
#define NUMBER_OF_SETS 8
#define ASSOCIATIVITY 4
#define TOTAL_BLOCKS MEMORY_SIZE/BLOCK_SIZE

#define INDEX_MASK 0x380

#define TAG_SIZE 6
#define INDEX_SIZE 3
#define OFFSET_SIZE 7

#define FLUSH_COMMAND_TEXT "FLUSH"
#define READ_COMMAND_TEXT "R"
#define WRITE_COMMAND_TEXT "W"
#define MISS_RATE_COMMAND_TEXT "MR"


#define SUCCESS 0
#define ERROR -1

#define ARGUMENTS_FLUSH 2
#define ARGUMENTS_MISS_RATE 2
#define ARGUMENTS_READ 3
#define ARGUMENTS_WRITE 4
